In [1]:
import numpy as np
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
#df.to_csv('example',index=False)

In [20]:
shuttle = pd.read_csv('Shuttle.csv')
shuttle_test = pd.read_csv('shuttle_tst.txt',sep =' ', names=['v1','v2','v3','v4','v5','v6','v7','v8','v9','Class'])
shuttle_train = pd.read_csv('shuttle_train.txt',sep =' ',names=['v1','v2','v3','v4','v5','v6','v7','v8','v9','Class'])

In [26]:
shuttle_c = pd.concat([shuttle_test,shuttle_train],axis=0,sort=False)

In [4]:
shuttle['Class'].value_counts()

1    34108
4     6748
5     2458
3      132
2       37
7       11
6        6
Name: Class, dtype: int64

In [5]:
def classDetector(x):
    if x == 1:
        return 0
    else:
        return 1


In [6]:
shuttle.head()

v1  v2  v3  v4  v5  v6  v7  v8  v9  Class
0  50  21  77   0  28   0  27  48  22      2
1  55   0  92   0   0  26  36  92  56      4
2  53   0  82   0  52  -5  29  30   2      1
3  37   0  76   0  28  18  40  48   8      1
4  37   0  79   0  34 -26  43  46   2      1

In [24]:
shuttle['Class']=shuttle['Class'].apply(classDetector)

In [28]:
shuttle_c['Class']=shuttle_c['Class'].apply(classDetector)

In [29]:
shuttle_c.head()

v1  v2  v3  v4  v5  v6  v7  v8  v9  Class
0  55   0  81   0  -6  11  25  88  64      1
1  56   0  96   0  52  -4  40  44   4      1
2  50  -1  89  -7  50   0  39  40   2      0
3  53   9  79   0  42  -2  25  37  12      1
4  55   2  82   0  54  -6  26  28   2      0

In [30]:
shuttle_c['Class'].value_counts()

0    45586
1    12414
Name: Class, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

In [31]:
X = shuttle_c.drop('Class',axis=1)
y = shuttle_c['Class']

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [33]:
from sklearn.svm import SVC

In [42]:
model = SVC(kernel='linear')

In [43]:
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [44]:
predictions = model.predict(X_test)

In [45]:
from sklearn.metrics import classification_report,confusion_matrix

In [46]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          0       0.99      0.98      0.99     15036
          1       0.95      0.98      0.96      4104

avg / total       0.98      0.98      0.98     19140



In [47]:
print(confusion_matrix(y_test,predictions))

[[14807   229]
 [  101  4003]]


In [62]:
coef=model.coef_.ravel()

In [52]:
model.decision_function

<bound method BaseSVC.decision_function of SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)>

In [53]:
model.decision_function_shape

'ovr'

In [54]:
model.coef0

0.0

In [57]:
model.degree

3

model.intercept_

In [58]:
model.support_

array([   58,    68,   108, ..., 38747, 38775, 38793], dtype=int32)

In [329]:
coe=coef=model.coef_.ravel()


In [330]:
coe

array([-1.09790193e-01, -1.92291588e-03, -1.65063928e-02, -2.82659061e-03,
        4.96818230e-01,  3.60176738e-04, -6.59466455e-01,  7.25918401e-01,
       -9.49188379e-02])

In [116]:
coefr=abs(coef.reshape(1,9))

In [304]:
percent=np.linspace(0,1,10)
percent

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [118]:
dfCoef = pd.DataFrame(coefr,columns='v1 v2 v3 v4 v5 v6 v7 v8 v9'.split())

In [143]:
dfCoef

v1        v2        v3        v4        v5       v6        v7  \
0  0.10979  0.001923  0.016506  0.002827  0.496818  0.00036  0.659466   

         v8        v9  
0  0.725918  0.094919

In [145]:
dfCoef.columns

Index(['v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9'], dtype='object')

In [263]:
tDf=dfCoef.loc[:, (dfCoef>0.5).any()]

In [264]:
tDf

v7        v8
0  0.659466  0.725918

In [265]:
z=tDf.columns.values

In [266]:

zz=list(z)
zz

['v7', 'v8']

In [173]:
manualFeatures = pd.read_csv('importantFeatures.csv')

In [174]:
manualFeatures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
Important features    100 non-null object
dtypes: object(1)
memory usage: 880.0+ bytes


In [175]:
def sortAndSplit (x):
    a=x.split()
    return a.sort()

In [193]:
manualFeatures

Important features
0            v5,v9,v1
1               v9,v5
2               v9,v5
3               v5,v9
4            v5,v9,v1
5               v1,v5
6               v9,v1
7               v1,v5
8               v1,v5
9               v9,v1
10              v1,v5
11              v1,v5
12              v1,v5
13              v9,v1
14              v9,v5
15           v9,v5,v8
16              v5,v1
17              v5,v9
18              v1,v5
19              v5,v1
20           v5,v1,v9
21              v1,v5
22              v9,v5
23              v1,v5
24              v9,v5
25              v1,v5
26              v1,v9
27              v5,v1
28              v9,v5
29              v5,v1
..                ...
70              v5,v9
71              v9,v5
72              v9,v5
73              v5,v9
74              v5,v1
75              v1,v5
76              v5,v9
77              v1,v5
78              v5,v9
79              v5,v1
80              v5,v9
81              v5,v9
82              v1,v5
83              v1,v5
84              v1,v5
85              v5,v9
86              v5,v9
87              v1,v5
88              v1,v5
89              v9,v5
90              v1,v5
91              v5,v1
92              v9,v5
93              v5,v9
94              v5,v9
95              v5,v9
96              v5,v9
97              v5,v9
98              v5,v1
99              v5,v1

[100 rows x 1 columns]

['v5', 'v9', 'v1']
['v9', 'v5']
['v9', 'v5']
['v5', 'v9']
['v5', 'v9', 'v1']
['v1', 'v5']
['v9', 'v1']
['v1', 'v5']
['v1', 'v5']
['v9', 'v1']
['v1', 'v5']
['v1', 'v5']
['v1', 'v5']
['v9', 'v1']
['v9', 'v5']
['v9', 'v5', 'v8']
['v5', 'v1']
['v5', 'v9']
['v1', 'v5']
['v5', 'v1']
['v5', 'v1', 'v9']
['v1', 'v5']
['v9', 'v5']
['v1', 'v5']
['v9', 'v5']
['v1', 'v5']
['v1', 'v9']
['v5', 'v1']
['v9', 'v5']
['v5', 'v1']
['v1', 'v5']
['v5', 'v9']
['v5', 'v1']
['v5', 'v9']
['v1', 'v5']
['v9', 'v5']
['v9', 'v5']
['v9', 'v5']
['v5', 'v9']
['v5', 'v1']
['v9', 'v5']
['v5', 'v9']
['v5', 'v9']
['v1', 'v5']
['v1', 'v5']
['v5', 'v9']
['v1', 'v9']
['v5', 'v9']
['v9', 'v5']
['v5', 'v9']
['v5', 'v9']
['v5', 'v9']
['v5', 'v1']
['v5', 'v1']
['v1', 'v5']
['v9', 'v5']
['v1', 'v5']
['v5', 'v9']
['v5', 'v9']
['v5', 'v9']
['v5', 'v9']
['v9', 'v5']
['v9', 'v1']
['v1', 'v5']
['v9', 'v5']
['v5', 'v9']
['v9', 'v1']
['v1', 'v9']
['v5', 'v9']
['v1', 'v9']
['v5', 'v9']
['v9', 'v5']
['v9', 'v5']
['v5', 'v9']
['v5', 'v1']
[

In [254]:
list1='hamed gol hamed'.split()

In [255]:
list2='hamed gol hamed'.split()

In [256]:
a=set(list1).union(list2)
a

{'gol', 'hamed'}

In [257]:
b = len (list2)
b

3

In [297]:
def jaccard(lst1, lst2): 
    a = set(lst1).intersection(lst2)
    b = set(lst1).union(lst2)
    c = len(a)/len(b)
    return c

In [291]:
Intersection(list1,list2)

1.0

In [311]:
#dfCoef.to_csv('coeffff',index=False)

In [318]:
coefficiant = pd.read_csv('coeffff')

In [322]:
coefficiant

v1        v2        v3        v4        v5       v6        v7  \
0  0.10979  0.001923  0.016506  0.002827  0.496818  0.00036  0.659466   

         v8        v9  
0  0.725918  0.094919

In [323]:
def intersection(lst1, lst2): 
    return list(set(lst1) & set(lst2))

In [326]:
import csv
percent=np.linspace(0,1,20)
for per in percent:
    tDf=coefficiant.loc[:, (coefficiant>per).any()]
    zz=list(tDf.columns.values)
    with open('Histogram-based-feautures.csv', newline='\n') as csvfile:
        csv_reader=csv.reader(csvfile, delimiter='\n')
        line_count=0
        i=0
        summ = 0
        print('if threshold is {} the average distance is :'.format(per))
        for row in csv_reader:
            summ = summ + jaccard(row[0].split(','),zz)    
            avg = summ/100
        print (avg)

      

if threshold is 0.0 the average distance is :
0.2899999999999995
if threshold is 0.05263157894736842 the average distance is :
0.33299999999999996
if threshold is 0.10526315789473684 the average distance is :
0.20799999999999985
if threshold is 0.15789473684210525 the average distance is :
0.17666666666666664
if threshold is 0.21052631578947367 the average distance is :
0.17666666666666664
if threshold is 0.2631578947368421 the average distance is :
0.17666666666666664
if threshold is 0.3157894736842105 the average distance is :
0.17666666666666664
if threshold is 0.3684210526315789 the average distance is :
0.17666666666666664
if threshold is 0.42105263157894735 the average distance is :
0.17666666666666664
if threshold is 0.47368421052631576 the average distance is :
0.17666666666666664
if threshold is 0.5263157894736842 the average distance is :
0.06433333333333337
if threshold is 0.5789473684210527 the average distance is :
0.06433333333333337
if threshold is 0.631578947368421 the 